# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: false

# Setup
title:            Cora Meador
tagline:          'A Jekyll theme'
description:      'A brazen two-column <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that pairs a prominent sidebar with uncomplicated content. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:              https://cmdor.github.io
baseurl:          /

author:
  name:           'Cora Meador'
  url:            https://www.linkedin.com/in/cora-meador/

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/cmdor/cmdor.github.io
